
name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+449

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  cupertino_icons: ^1.0.6

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  cached_network_image: ^3.4.1

  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  google_maps_flutter: 2.6.1
  geolocator: ^10.1.1
  geocoding: ^3.0.0
  translator: ^1.0.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  app_links: ^3.4.1
  flutter_local_notifications: ^17.0.0
  in_app_purchase: 3.1.13
  http: ^1.2.2
  cloud_functions: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/groups/
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"