// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5N3_7sV2V_NzXiGKU_Uuu0JSYbtvLYJs',
    appId: '1:358333936335:web:c15f7f29ed67e6f654fdba',
    messagingSenderId: '358333936335',
    projectId: 'flutter-vietlove-dating',
    authDomain: 'flutter-vietlove-dating.firebaseapp.com',
    storageBucket: 'flutter-vietlove-dating.firebasestorage.app',
    measurementId: 'G-GXH461SV4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dkZ4xBAZ-rUg1TUmYyKYwuXLwXS0Fys',
    appId: '1:358333936335:android:fecb842f4ba2966354fdba',
    messagingSenderId: '358333936335',
    projectId: 'flutter-vietlove-dating',
    storageBucket: 'flutter-vietlove-dating.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5xBmU_Qpr4PsCOYRsz6Ldjh4wIyl3zi4',
    appId: '1:358333936335:ios:bc1ccdedc805d0fa54fdba',
    messagingSenderId: '358333936335',
    projectId: 'flutter-vietlove-dating',
    storageBucket: 'flutter-vietlove-dating.firebasestorage.app',
    iosBundleId: 'com.vietlovedating.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5xBmU_Qpr4PsCOYRsz6Ldjh4wIyl3zi4',
    appId: '1:358333936335:ios:bc1ccdedc805d0fa54fdba',
    messagingSenderId: '358333936335',
    projectId: 'flutter-vietlove-dating',
    storageBucket: 'flutter-vietlove-dating.firebasestorage.app',
    iosBundleId: 'com.vietlovedating.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5N3_7sV2V_NzXiGKU_Uuu0JSYbtvLYJs',
    appId: '1:358333936335:web:0f0c7d25670795b754fdba',
    messagingSenderId: '358333936335',
    projectId: 'flutter-vietlove-dating',
    authDomain: 'flutter-vietlove-dating.firebaseapp.com',
    storageBucket: 'flutter-vietlove-dating.firebasestorage.app',
    measurementId: 'G-J1PCBG1Z5S',
  );
}
