import 'package:flutter/foundation.dart';

class VocabItem {
  final String en;
  final String vi;
  const VocabItem(this.en, this.vi);
}

const easyVerbs = <VocabItem>[
  VocabItem('be', 'là / thì / ở'),
  VocabItem('have', 'có'),
  VocabItem('do', 'làm'),
  VocabItem('go', 'đi'),
  VocabItem('come', 'đến'),
  VocabItem('get', 'nhận / lấy / có được'),
  VocabItem('make', 'làm / tạo ra'),
  VocabItem('take', 'lấy / mang'),
  VocabItem('give', 'cho'),
  VocabItem('know', 'biết'),
  VocabItem('think', 'nghĩ'),
  VocabItem('want', 'muốn'),
  VocabItem('need', 'cần'),
  VocabItem('like', 'thích'),
  VocabItem('love', 'yêu / rất thích'),
  VocabItem('look', 'nhìn'),
  VocabItem('see', 'nhìn thấy'),
  VocabItem('watch', 'xem'),
  VocabItem('hear', 'nghe thấy'),
  VocabItem('listen', 'lắng nghe'),
  VocabItem('say', 'nói'),
  VocabItem('tell', 'nói / kể cho'),
  VocabItem('speak', 'nói'),
  VocabItem('talk', 'nói chuyện'),
  VocabItem('ask', 'hỏi'),
  VocabItem('answer', 'trả lời'),
  VocabItem('call', 'gọi'),
  VocabItem('help', 'giúp'),
  VocabItem('use', 'sử dụng'),
  VocabItem('find', 'tìm thấy'),
  VocabItem('keep', 'giữ'),
  VocabItem('put', 'đặt / để'),
  VocabItem('bring', 'mang đến'),
  VocabItem('buy', 'mua'),
  VocabItem('pay', 'trả tiền'),
  VocabItem('sell', 'bán'),
  VocabItem('eat', 'ăn'),
  VocabItem('drink', 'uống'),
  VocabItem('cook', 'nấu ăn'),
  VocabItem('sleep', 'ngủ'),
  VocabItem('wake', 'thức dậy'),
  VocabItem('sit', 'ngồi'),
  VocabItem('stand', 'đứng'),
  VocabItem('walk', 'đi bộ'),
  VocabItem('run', 'chạy'),
  VocabItem('drive', 'lái xe'),
  VocabItem('ride', 'đi / cưỡi'),
  VocabItem('wait', 'chờ'),
  VocabItem('start', 'bắt đầu'),
  VocabItem('stop', 'dừng lại'),
  VocabItem('open', 'mở'),
  VocabItem('close', 'đóng'),
  VocabItem('turn', 'quay / bật / tắt'),
  VocabItem('move', 'di chuyển'),
  VocabItem('stay', 'ở lại'),
  VocabItem('leave', 'rời đi'),
  VocabItem('live', 'sống'),
  VocabItem('work', 'làm việc'),
  VocabItem('study', 'học'),
  VocabItem('learn', 'học / học cách'),
  VocabItem('teach', 'dạy'),
  VocabItem('read', 'đọc'),
  VocabItem('write', 'viết'),
  VocabItem('send', 'gửi'),
  VocabItem('show', 'cho xem / chỉ'),
  VocabItem('meet', 'gặp'),
  VocabItem('visit', 'thăm'),
  VocabItem('remember', 'nhớ'),
  VocabItem('forget', 'quên'),
  VocabItem('understand', 'hiểu'),
  VocabItem('explain', 'giải thích'),
  VocabItem('choose', 'chọn'),
  VocabItem('try', 'thử / cố gắng'),
  VocabItem('plan', 'lên kế hoạch'),
  VocabItem('hope', 'hy vọng'),
  VocabItem('feel', 'cảm thấy'),
  VocabItem('seem', 'có vẻ'),
  VocabItem('become', 'trở thành'),
  VocabItem('happen', 'xảy ra'),
  VocabItem('change', 'thay đổi'),
  VocabItem('check', 'kiểm tra'),
  VocabItem('clean', 'dọn dẹp / làm sạch'),
  VocabItem('wash', 'rửa / giặt'),
  VocabItem('wear', 'mặc / đeo'),
  VocabItem('carry', 'mang / xách'),
  VocabItem('hold', 'cầm / giữ'),
  VocabItem('cut', 'cắt'),
  VocabItem('break', 'làm vỡ / hỏng'),
  VocabItem('fix', 'sửa'),
  VocabItem('build', 'xây / dựng'),
  VocabItem('join', 'tham gia'),
  VocabItem('follow', 'theo dõi / đi theo'),
  VocabItem('win', 'thắng'),
  VocabItem('lose', 'thua / mất'),
  VocabItem('grow', 'lớn lên / phát triển'),
  VocabItem('believe', 'tin'),
  VocabItem('agree', 'đồng ý'),
  VocabItem('decide', 'quyết định'),
  VocabItem('continue', 'tiếp tục'),
  VocabItem('finish', 'hoàn thành'),
];

const everydayWords = <VocabItem>[
  VocabItem('account', 'tài khoản'),
  VocabItem('address', 'địa chỉ'),
  VocabItem('adult', 'người lớn'),
  VocabItem('airport', 'sân bay'),
  VocabItem('animal', 'động vật'),
  VocabItem('appointment', 'cuộc hẹn'),
  VocabItem('area', 'khu vực'),
  VocabItem('article', 'bài viết'),
  VocabItem('baby', 'em bé'),
  VocabItem('bag', 'túi'),
  VocabItem('ball', 'quả bóng'),
  VocabItem('bank', 'ngân hàng'),
  VocabItem('bath', 'bồn tắm'),
  VocabItem('beach', 'bãi biển'),
  VocabItem('bed', 'giường'),
  VocabItem('bedroom', 'phòng ngủ'),
  VocabItem('bike', 'xe đạp'),
  VocabItem('birthday', 'sinh nhật'),
  VocabItem('blanket', 'chăn'),
  VocabItem('book', 'sách'),
  VocabItem('bottle', 'chai'),
  VocabItem('box', 'hộp'),
  VocabItem('breakfast', 'bữa sáng'),
  VocabItem('building', 'tòa nhà'),
  VocabItem('bus', 'xe buýt'),
  VocabItem('business', 'doanh nghiệp'),
  VocabItem('calendar', 'lịch'),
  VocabItem('camera', 'máy ảnh'),
  VocabItem('car', 'xe hơi'),
  VocabItem('card', 'thẻ'),
  VocabItem('cash', 'tiền mặt'),
  VocabItem('cat', 'con mèo'),
  VocabItem('center', 'trung tâm'),
  VocabItem('chair', 'ghế'),
  VocabItem('chance', 'cơ hội'),
  VocabItem('class', 'lớp học'),
  VocabItem('clock', 'đồng hồ'),
  VocabItem('clothes', 'quần áo'),
  VocabItem('coat', 'áo khoác'),
  VocabItem('coffee', 'cà phê'),
  VocabItem('college', 'trường cao đẳng'),
  VocabItem('company', 'công ty'),
  VocabItem('computer', 'máy tính'),
  VocabItem('conversation', 'cuộc trò chuyện'),
  VocabItem('corner', 'góc'),
  VocabItem('country', 'đất nước'),
  VocabItem('customer', 'khách hàng'),
  VocabItem('date', 'buổi hẹn / ngày'),
  VocabItem('day', 'ngày'),
  VocabItem('desk', 'bàn làm việc'),
  VocabItem('dinner', 'bữa tối'),
  VocabItem('doctor', 'bác sĩ'),
  VocabItem('door', 'cửa'),
  VocabItem('dream', 'giấc mơ'),
  VocabItem('driver', 'tài xế'),
  VocabItem('email', 'email'),
  VocabItem('event', 'sự kiện'),
  VocabItem('family', 'gia đình'),
  VocabItem('farm', 'nông trại'),
  VocabItem('field', 'cánh đồng / lĩnh vực'),
  VocabItem('film', 'bộ phim'),
  VocabItem('floor', 'sàn / tầng'),
  VocabItem('flower', 'hoa'),
  VocabItem('food', 'đồ ăn'),
  VocabItem('friend', 'bạn'),
  VocabItem('fruit', 'trái cây'),
  VocabItem('garden', 'khu vườn'),
  VocabItem('gift', 'quà'),
  VocabItem('glass', 'ly / kính'),
  VocabItem('goal', 'mục tiêu'),
  VocabItem('group', 'nhóm'),
  VocabItem('guest', 'khách'),
  VocabItem('gym', 'phòng gym'),
  VocabItem('hair', 'tóc'),
  VocabItem('head', 'đầu'),
  VocabItem('heart', 'trái tim'),
  VocabItem('holiday', 'kỳ nghỉ'),
  VocabItem('home', 'nhà'),
  VocabItem('homework', 'bài tập về nhà'),
  VocabItem('hospital', 'bệnh viện'),
  VocabItem('hotel', 'khách sạn'),
  VocabItem('house', 'ngôi nhà'),
  VocabItem('idea', 'ý tưởng'),
  VocabItem('internet', 'mạng internet'),
  VocabItem('key', 'chìa khóa'),
  VocabItem('kitchen', 'nhà bếp'),
  VocabItem('language', 'ngôn ngữ'),
  VocabItem('lunch', 'bữa trưa'),
  VocabItem('map', 'bản đồ'),
  VocabItem('market', 'chợ'),
  VocabItem('meal', 'bữa ăn'),
  VocabItem('meeting', 'cuộc họp'),
  VocabItem('member', 'thành viên'),
  VocabItem('message', 'tin nhắn'),
  VocabItem('minute', 'phút'),
  VocabItem('money', 'tiền'),
  VocabItem('month', 'tháng'),
  VocabItem('morning', 'buổi sáng'),
  VocabItem('movie', 'bộ phim'),
  VocabItem('music', 'âm nhạc'),
  VocabItem('name', 'tên'),
  VocabItem('neighbor', 'hàng xóm'),
  VocabItem('news', 'tin tức'),
  VocabItem('night', 'ban đêm'),
  VocabItem('number', 'số'),
  VocabItem('office', 'văn phòng'),
  VocabItem('page', 'trang'),
  VocabItem('parent', 'bố mẹ'),
  VocabItem('party', 'bữa tiệc'),
  VocabItem('password', 'mật khẩu'),
  VocabItem('phone', 'điện thoại'),
  VocabItem('photo', 'bức ảnh'),
  VocabItem('picture', 'bức tranh / ảnh'),
  VocabItem('place', 'nơi'),
  VocabItem('price', 'giá'),
  VocabItem('problem', 'vấn đề'),
  VocabItem('question', 'câu hỏi'),
  VocabItem('restaurant', 'nhà hàng'),
  VocabItem('road', 'con đường'),
  VocabItem('room', 'phòng'),
  VocabItem('school', 'trường học'),
  VocabItem('service', 'dịch vụ'),
  VocabItem('shop', 'cửa hàng'),
  VocabItem('shower', 'vòi sen / việc tắm'),
  VocabItem('sister', 'chị/em gái'),
  VocabItem('size', 'kích cỡ'),
  VocabItem('song', 'bài hát'),
  VocabItem('sport', 'thể thao'),
  VocabItem('station', 'ga / trạm'),
  VocabItem('story', 'câu chuyện'),
  VocabItem('street', 'đường phố'),
  VocabItem('student', 'học sinh / sinh viên'),
  VocabItem('supermarket', 'siêu thị'),
  VocabItem('table', 'bàn'),
  VocabItem('team', 'đội / nhóm'),
  VocabItem('ticket', 'vé'),
  VocabItem('time', 'thời gian'),
  VocabItem('town', 'thị trấn'),
  VocabItem('train', 'tàu hỏa'),
  VocabItem('travel', 'du lịch'),
  VocabItem('trip', 'chuyến đi'),
  VocabItem('video', 'video'),
  VocabItem('voice', 'giọng nói'),
  VocabItem('water', 'nước'),
  VocabItem('weather', 'thời tiết'),
  VocabItem('week', 'tuần'),
  VocabItem('weekend', 'cuối tuần'),
  VocabItem('wife', 'vợ'),
  VocabItem('husband', 'chồng'),
  VocabItem('world', 'thế giới'),
  VocabItem('year', 'năm'),
  VocabItem('yesterday', 'hôm qua'),
  VocabItem('today', 'hôm nay'),
  VocabItem('tomorrow', 'ngày mai'),
  VocabItem('apple', 'quả táo'),
  VocabItem('banana', 'quả chuối'),
  VocabItem('orange', 'quả cam'),
  VocabItem('rice', 'cơm / gạo'),
  VocabItem('bread', 'bánh mì'),
  VocabItem('chicken', 'thịt gà'),
  VocabItem('beef', 'thịt bò'),
  VocabItem('fish', 'cá'),
  VocabItem('milk', 'sữa'),
  VocabItem('tea', 'trà'),
  VocabItem('choice', 'lựa chọn'),
  VocabItem('contact', 'liên hệ'),
  VocabItem('cost', 'chi phí'),
  VocabItem('direction', 'phương hướng'),
  VocabItem('example', 'ví dụ'),
  VocabItem('experience', 'kinh nghiệm'),
  VocabItem('future', 'tương lai'),
  VocabItem('information', 'thông tin'),
  VocabItem('interest', 'sở thích'),
  VocabItem('life', 'cuộc sống'),
  VocabItem('location', 'vị trí'),
  VocabItem('reason', 'lý do'),
  VocabItem('relationship', 'mối quan hệ'),
  VocabItem('result', 'kết quả'),
  VocabItem('schedule', 'lịch trình'),
  VocabItem('support', 'sự hỗ trợ'),
  VocabItem('thing', 'đồ vật / điều'),
  VocabItem('way', 'cách / con đường'),
  VocabItem('word', 'từ'),
  VocabItem('address book', 'danh bạ'),
  VocabItem('bus stop', 'trạm xe buýt'),
  VocabItem('coffee shop', 'quán cà phê'),
  VocabItem('dining room', 'phòng ăn'),
  VocabItem('front door', 'cửa trước'),
  VocabItem('living room', 'phòng khách'),
  VocabItem('parking lot', 'bãi đỗ xe'),
  VocabItem('shopping center', 'trung tâm mua sắm'),
  VocabItem('train station', 'ga tàu'),
  VocabItem('workplace', 'nơi làm việc'),
  VocabItem('backpack', 'ba lô'),
  VocabItem('wallet', 'ví'),
  VocabItem('umbrella', 'ô / dù'),
  VocabItem('jacket', 'áo khoác'),
  VocabItem('shirt', 'áo sơ mi'),
  VocabItem('shoes', 'giày'),
  VocabItem('socks', 'vớ'),
  VocabItem('pants', 'quần'),
  VocabItem('dress', 'váy / đầm'),
  VocabItem('kitchen table', 'bàn bếp'),
  VocabItem('bedside table', 'bàn cạnh giường'),
  VocabItem('phone charger', 'sạc điện thoại'),
  VocabItem('laptop', 'máy tính xách tay'),
  VocabItem('keyboard', 'bàn phím'),
  VocabItem('screen', 'màn hình'),
  VocabItem('website', 'trang web'),
  VocabItem('password reset', 'đặt lại mật khẩu'),
  VocabItem('online class', 'lớp học trực tuyến'),
  VocabItem('video call', 'cuộc gọi video'),
  VocabItem('voice message', 'tin nhắn thoại'),
  VocabItem('social media', 'mạng xã hội'),
  VocabItem('profile', 'hồ sơ'),
  VocabItem('photo album', 'album ảnh'),
  VocabItem('family member', 'thành viên gia đình'),
  VocabItem('best friend', 'bạn thân'),
  VocabItem('boyfriend', 'bạn trai'),
  VocabItem('girlfriend', 'bạn gái'),
  VocabItem('community', 'cộng đồng'),
  VocabItem('birthday party', 'tiệc sinh nhật'),
  VocabItem('dinner table', 'bàn ăn'),
  VocabItem('shopping list', 'danh sách mua sắm'),
  VocabItem('grocery store', 'cửa hàng tạp hóa'),
  VocabItem('food court', 'khu ăn uống'),
  VocabItem('bus ticket', 'vé xe buýt'),
  VocabItem('train ticket', 'vé tàu'),
  VocabItem('parking ticket', 'vé phạt đỗ xe'),
  VocabItem('office chair', 'ghế văn phòng'),
  VocabItem('work meeting', 'cuộc họp công việc'),
  VocabItem('team leader', 'trưởng nhóm'),
  VocabItem('pay day', 'ngày nhận lương'),
  VocabItem('bank account', 'tài khoản ngân hàng'),
  VocabItem('credit card', 'thẻ tín dụng'),
  VocabItem('debit card', 'thẻ ghi nợ'),
  VocabItem('phone number', 'số điện thoại'),
  VocabItem('email address', 'địa chỉ email'),
  VocabItem('home address', 'địa chỉ nhà'),
  VocabItem('emergency contact', 'người liên hệ khẩn cấp'),
  VocabItem('afternoon', 'buổi chiều'),
  VocabItem('evening', 'buổi tối'),
  VocabItem('age', 'tuổi'),
  VocabItem('boy', 'cậu bé'),
  VocabItem('girl', 'cô bé / cô gái'),
  VocabItem('man', 'đàn ông'),
  VocabItem('woman', 'phụ nữ'),
  VocabItem('person', 'người'),
  VocabItem('people', 'mọi người'),
  VocabItem('child', 'đứa trẻ'),
];

const advancedWords = <VocabItem>[
  VocabItem('abundant', 'dồi dào'),
  VocabItem('accurate', 'chính xác'),
  VocabItem('adaptable', 'dễ thích nghi'),
  VocabItem('adequate', 'đầy đủ'),
  VocabItem('ambiguous', 'mơ hồ'),
  VocabItem('ambitious', 'có tham vọng'),
  VocabItem('apparent', 'rõ ràng / có vẻ'),
  VocabItem('appropriate', 'phù hợp'),
  VocabItem('beneficial', 'có lợi'),
  VocabItem('capable', 'có khả năng'),
  VocabItem('coherent', 'mạch lạc'),
  VocabItem('compelling', 'thuyết phục'),
  VocabItem('comprehensive', 'toàn diện'),
  VocabItem('considerable', 'đáng kể'),
  VocabItem('consistent', 'nhất quán'),
  VocabItem('convenient', 'thuận tiện'),
  VocabItem('crucial', 'cực kỳ quan trọng'),
  VocabItem('efficient', 'hiệu quả'),
  VocabItem('essential', 'thiết yếu'),
  VocabItem('flexible', 'linh hoạt'),
  VocabItem('frequent', 'thường xuyên'),
  VocabItem('genuine', 'chân thật'),
  VocabItem('independent', 'độc lập'),
  VocabItem('inevitable', 'không thể tránh khỏi'),
  VocabItem('obvious', 'hiển nhiên'),
  VocabItem('reliable', 'đáng tin cậy'),
  VocabItem('significant', 'đáng kể / quan trọng'),
  VocabItem('sufficient', 'đủ'),
  VocabItem('temporary', 'tạm thời'),
  VocabItem('valuable', 'có giá trị'),
  VocabItem('versatile', 'đa năng'),
  VocabItem('vulnerable', 'dễ bị tổn thương'),
  VocabItem('accurately', 'một cách chính xác'),
  VocabItem('approximately', 'xấp xỉ'),
  VocabItem('eventually', 'cuối cùng'),
  VocabItem('frequently', 'thường xuyên'),
  VocabItem('gradually', 'dần dần'),
  VocabItem('immediately', 'ngay lập tức'),
  VocabItem('occasionally', 'thỉnh thoảng'),
  VocabItem('particularly', 'đặc biệt'),
  VocabItem('personally', 'cá nhân'),
  VocabItem('probably', 'có lẽ'),
  VocabItem('recently', 'gần đây'),
  VocabItem('usually', 'thường'),
  VocabItem('apparently', 'dường như'),
  VocabItem('essentially', 'về cơ bản'),
  VocabItem('absolutely', 'hoàn toàn'),
  VocabItem('actually', 'thực ra'),
  VocabItem('confident', 'tự tin'),
  VocabItem('curious', 'tò mò'),
  VocabItem('generous', 'hào phóng'),
  VocabItem('patient', 'kiên nhẫn'),
  VocabItem('responsible', 'có trách nhiệm'),
  VocabItem('sensitive', 'nhạy cảm'),
  VocabItem('practical', 'thực tế'),
  VocabItem('professional', 'chuyên nghiệp'),
  VocabItem('reasonable', 'hợp lý'),
  VocabItem('serious', 'nghiêm túc'),
  VocabItem('specific', 'cụ thể'),
  VocabItem('typical', 'điển hình'),
  VocabItem('unexpected', 'bất ngờ'),
  VocabItem('opportunity', 'cơ hội'),
  VocabItem('environment', 'môi trường'),
  VocabItem('communication', 'giao tiếp'),
  VocabItem('decision', 'quyết định'),
  VocabItem('development', 'sự phát triển'),
  VocabItem('education', 'giáo dục'),
  VocabItem('responsibility', 'trách nhiệm'),
  VocabItem('confidence', 'sự tự tin'),
  VocabItem('knowledge', 'kiến thức'),
  VocabItem('behavior', 'hành vi'),
  VocabItem('advantage', 'lợi thế'),
  VocabItem('challenge', 'thách thức'),
  VocabItem('solution', 'giải pháp'),
  VocabItem('situation', 'tình huống'),
  VocabItem('priority', 'ưu tiên'),
  VocabItem('requirement', 'yêu cầu'),
  VocabItem('recommendation', 'lời khuyên / đề xuất'),
  VocabItem('possibility', 'khả năng'),
  VocabItem('impression', 'ấn tượng'),
  VocabItem('attention', 'sự chú ý'),
  VocabItem('agreement', 'sự đồng ý'),
  VocabItem('difference', 'sự khác biệt'),
  VocabItem('discussion', 'cuộc thảo luận'),
  VocabItem('improvement', 'sự cải thiện'),
  VocabItem('permission', 'sự cho phép'),
  VocabItem('preference', 'sự ưu tiên / sở thích'),
  VocabItem('purpose', 'mục đích'),
  VocabItem('quality', 'chất lượng'),
  VocabItem('resource', 'nguồn lực'),
  VocabItem('strategy', 'chiến lược'),
  VocabItem('successful', 'thành công'),
  VocabItem('comfortable', 'thoải mái'),
  VocabItem('effective', 'hiệu quả'),
  VocabItem('familiar', 'quen thuộc'),
  VocabItem('necessary', 'cần thiết'),
  VocabItem('available', 'có sẵn'),
  VocabItem('alternative', 'phương án thay thế'),
  VocabItem('analysis', 'sự phân tích'),
  VocabItem('assessment', 'sự đánh giá'),
  VocabItem('awareness', 'nhận thức'),
  VocabItem('capacity', 'năng lực'),
  VocabItem('circumstance', 'hoàn cảnh'),
  VocabItem('complexity', 'độ phức tạp'),
  VocabItem('consequence', 'hậu quả'),
  VocabItem('context', 'bối cảnh'),
  VocabItem('contribution', 'sự đóng góp'),
  VocabItem('criteria', 'tiêu chí'),
  VocabItem('distribution', 'sự phân phối'),
  VocabItem('emphasis', 'sự nhấn mạnh'),
  VocabItem('factor', 'yếu tố'),
  VocabItem('impact', 'tác động'),
  VocabItem('influence', 'ảnh hưởng'),
  VocabItem('initiative', 'sáng kiến'),
  VocabItem('interpretation', 'sự diễn giải'),
  VocabItem('objective', 'mục tiêu'),
  VocabItem('outcome', 'kết quả'),
  VocabItem('perspective', 'góc nhìn'),
  VocabItem('potential', 'tiềm năng'),
  VocabItem('principle', 'nguyên tắc'),
  VocabItem('procedure', 'quy trình'),
  VocabItem('process', 'quá trình'),
  VocabItem('progress', 'tiến bộ'),
  VocabItem('proportion', 'tỷ lệ'),
  VocabItem('recognition', 'sự công nhận'),
  VocabItem('response', 'phản hồi'),
  VocabItem('standard', 'tiêu chuẩn'),
  VocabItem('structure', 'cấu trúc'),
  VocabItem('tendency', 'xu hướng'),
  VocabItem('trend', 'xu hướng'),
  VocabItem('variation', 'sự biến đổi'),
  VocabItem('cooperation', 'sự hợp tác'),
  VocabItem('participation', 'sự tham gia'),
  VocabItem('qualification', 'trình độ / bằng cấp'),
  VocabItem('employment', 'việc làm'),
  VocabItem('occupation', 'nghề nghiệp'),
  VocabItem('professionalism', 'tính chuyên nghiệp'),
  VocabItem('productivity', 'năng suất'),
  VocabItem('negotiation', 'đàm phán'),
  VocabItem('presentation', 'bài thuyết trình'),
  VocabItem('performance', 'hiệu suất'),
  VocabItem('leadership', 'khả năng lãnh đạo'),
  VocabItem('motivation', 'động lực'),
  VocabItem('discipline', 'kỷ luật'),
  VocabItem('reputation', 'danh tiếng'),
  VocabItem('privacy', 'quyền riêng tư'),
  VocabItem('security', 'bảo mật'),
  VocabItem('technology', 'công nghệ'),
  VocabItem('digital', 'kỹ thuật số'),
  VocabItem('financial', 'tài chính'),
  VocabItem('economic', 'kinh tế'),
  VocabItem('cultural', 'văn hóa'),
  VocabItem('environmental', 'thuộc môi trường'),
  VocabItem('international', 'quốc tế'),
  VocabItem('traditional', 'truyền thống'),
  VocabItem('individual', 'cá nhân'),
  VocabItem('abandon', 'bỏ, từ bỏ'),
  VocabItem('abrupt', 'đột ngột'),
  VocabItem('absurd', 'vô lý'),
  VocabItem('accelerate', 'tăng tốc'),
  VocabItem('accessible', 'dễ tiếp cận'),
  VocabItem('accomplish', 'hoàn thành'),
  VocabItem('accountable', 'chịu trách nhiệm'),
  VocabItem('accumulate', 'tích lũy'),
  VocabItem('acknowledge', 'thừa nhận'),
  VocabItem('acquire', 'đạt được, có được'),
  VocabItem('acute', 'cấp tính, nghiêm trọng'),
  VocabItem('adjacent', 'kề bên'),
  VocabItem('advocate', 'ủng hộ, người ủng hộ'),
  VocabItem('allocate', 'phân bổ'),
  VocabItem('alter', 'thay đổi'),
  VocabItem('anticipate', 'dự đoán trước'),
  VocabItem('appreciate', 'trân trọng, đánh giá cao'),
  VocabItem('arbitrary', 'tùy ý, độc đoán'),
  VocabItem('articulate', 'diễn đạt rõ ràng'),
  VocabItem('aspire', 'khát khao, hướng tới'),
  VocabItem('attain', 'đạt được'),
  VocabItem('attribute', 'quy cho, đặc điểm'),
  VocabItem('authentic', 'chân thực'),
  VocabItem('autonomous', 'tự chủ'),
  VocabItem('bias', 'thiên kiến'),
  VocabItem('bolster', 'củng cố'),
  VocabItem('breach', 'vi phạm, lỗ hổng'),
  VocabItem('brief', 'ngắn gọn'),
  VocabItem('bulk', 'phần lớn'),
  VocabItem('cease', 'chấm dứt'),
  VocabItem('clarify', 'làm rõ'),
  VocabItem('collaborate', 'hợp tác'),
  VocabItem('commence', 'bắt đầu'),
  VocabItem('compensate', 'bù đắp'),
  VocabItem('compile', 'tổng hợp'),
  VocabItem('complement', 'bổ sung'),
  VocabItem('comprise', 'bao gồm'),
  VocabItem('conceive', 'hình thành ý tưởng'),
  VocabItem('concurrent', 'đồng thời'),
  VocabItem('confine', 'giới hạn'),
  VocabItem('conform', 'tuân thủ'),
  VocabItem('consent', 'sự đồng ý'),
  VocabItem('constrain', 'hạn chế'),
  VocabItem('consult', 'tham khảo'),
  VocabItem('contemplate', 'cân nhắc kỹ'),
  VocabItem('contradict', 'mâu thuẫn'),
  VocabItem('controversial', 'gây tranh cãi'),
  VocabItem('convey', 'truyền đạt'),
  VocabItem('convince', 'thuyết phục'),
  VocabItem('coordinate', 'phối hợp'),
  VocabItem('correspond', 'phù hợp, tương ứng'),
  VocabItem('credible', 'đáng tin'),
  VocabItem('cumulative', 'tích lũy'),
  VocabItem('deduce', 'suy luận'),
  VocabItem('demonstrate', 'chứng minh, thể hiện'),
  VocabItem('denote', 'biểu thị'),
  VocabItem('depict', 'miêu tả'),
  VocabItem('derive', 'bắt nguồn, suy ra'),
  VocabItem('deter', 'ngăn cản'),
  VocabItem('diminish', 'giảm bớt'),
  VocabItem('discrete', 'tách biệt'),
  VocabItem('distinct', 'khác biệt rõ ràng'),
  VocabItem('diverse', 'đa dạng'),
  VocabItem('dominate', 'chi phối'),
  VocabItem('elaborate', 'chi tiết, công phu'),
  VocabItem('eliminate', 'loại bỏ'),
  VocabItem('empirical', 'dựa trên thực nghiệm'),
  VocabItem('encounter', 'gặp phải'),
  VocabItem('enhance', 'nâng cao'),
  VocabItem('enormous', 'khổng lồ'),
  VocabItem('ensure', 'đảm bảo'),
  VocabItem('equivalent', 'tương đương'),
  VocabItem('erode', 'xói mòn'),
  VocabItem('ethical', 'có đạo đức'),
  VocabItem('evaluate', 'đánh giá'),
  VocabItem('exclude', 'loại trừ'),
  VocabItem('explicit', 'rõ ràng, cụ thể'),
  VocabItem('exploit', 'khai thác, bóc lột'),
  VocabItem('facilitate', 'tạo điều kiện'),
  VocabItem('feasible', 'khả thi'),
  VocabItem('fluctuate', 'dao động'),
  VocabItem('forthcoming', 'sắp tới'),
  VocabItem('fundamental', 'cơ bản, nền tảng'),
  VocabItem('generate', 'tạo ra'),
  VocabItem('hence', 'do đó'),
  VocabItem('hierarchy', 'thứ bậc'),
  VocabItem('highlight', 'làm nổi bật'),
  VocabItem('hypothesis', 'giả thuyết'),
  VocabItem('identical', 'giống hệt'),
  VocabItem('implement', 'triển khai'),
  VocabItem('implicit', 'ngầm hiểu'),
  VocabItem('incentive', 'động lực, ưu đãi'),
  VocabItem('incorporate', 'tích hợp'),
  VocabItem('induce', 'gây ra, khiến'),
  VocabItem('inequality', 'bất bình đẳng'),
  VocabItem('inherent', 'vốn có'),
  VocabItem('innovative', 'sáng tạo'),
  VocabItem('inspect', 'kiểm tra kỹ'),
  VocabItem('integrate', 'tích hợp'),
  VocabItem('integrity', 'chính trực'),
  VocabItem('intervene', 'can thiệp'),
  VocabItem('intrinsic', 'thuộc bản chất'),
  VocabItem('justify', 'biện minh, chứng minh là hợp lý'),
  VocabItem('legitimate', 'hợp pháp, chính đáng'),
  VocabItem('likewise', 'tương tự'),
  VocabItem('magnitude', 'mức độ, quy mô'),
  VocabItem('mandatory', 'bắt buộc'),
  VocabItem('manipulate', 'thao túng'),
  VocabItem('marginal', 'nhỏ, không đáng kể'),
  VocabItem('mediation', 'hòa giải'),
  VocabItem('mutual', 'lẫn nhau'),
  VocabItem('nevertheless', 'tuy vậy'),
  VocabItem('notion', 'khái niệm'),
  VocabItem('obtain', 'đạt được'),
  VocabItem('ongoing', 'đang diễn ra'),
  VocabItem('orient', 'định hướng'),
  VocabItem('paradigm', 'mô hình, hệ hình'),
  VocabItem('persist', 'tiếp tục tồn tại'),
  VocabItem('plausible', 'có vẻ hợp lý'),
  VocabItem('precise', 'chính xác'),
  VocabItem('predominant', 'chủ yếu'),
  VocabItem('preliminary', 'sơ bộ'),
  VocabItem('presume', 'cho rằng'),
  VocabItem('profound', 'sâu sắc'),
  VocabItem('prominent', 'nổi bật'),
  VocabItem('prohibit', 'cấm'),
  VocabItem('provoke', 'gây ra, kích động'),
  VocabItem('pursue', 'theo đuổi'),
  VocabItem('rational', 'hợp lý'),
  VocabItem('refine', 'tinh chỉnh'),
  VocabItem('relevant', 'liên quan'),
  VocabItem('reluctant', 'miễn cưỡng'),
  VocabItem('resilient', 'kiên cường'),
  VocabItem('retain', 'giữ lại'),
  VocabItem('reveal', 'tiết lộ'),
  VocabItem('rigid', 'cứng nhắc'),
  VocabItem('robust', 'vững chắc'),
  VocabItem('scenario', 'kịch bản'),
  VocabItem('scrutinize', 'xem xét kỹ'),
  VocabItem('simulate', 'mô phỏng'),
  VocabItem('sole', 'duy nhất'),
  VocabItem('subsequent', 'tiếp theo'),
  VocabItem('substantial', 'đáng kể'),
  VocabItem('sustain', 'duy trì'),
  VocabItem('terminate', 'chấm dứt'),
  VocabItem('thereby', 'nhờ đó'),
  VocabItem('undergo', 'trải qua'),
  VocabItem('underlying', 'tiềm ẩn, nền tảng'),
  VocabItem('unify', 'thống nhất'),
  VocabItem('utilize', 'tận dụng'),
  VocabItem('valid', 'hợp lệ'),
  VocabItem('whereas', 'trong khi'),
  VocabItem('widespread', 'phổ biến rộng rãi'),
  VocabItem('withdraw', 'rút lại, rút lui'),
  VocabItem('yield', 'mang lại, sản lượng'),
  VocabItem('absorption', 'sự hấp thụ'),
  VocabItem('acceleration', 'sự tăng tốc'),
  VocabItem('accessibility', 'khả năng tiếp cận'),
  VocabItem('accommodation', 'chỗ ở'),
  VocabItem('accusation', 'lời cáo buộc'),
  VocabItem('adaptation', 'sự thích nghi'),
  VocabItem('administration', 'sự quản lý'),
  VocabItem('admission', 'sự thừa nhận, nhập học'),
  VocabItem('adolescent', 'thanh thiếu niên'),
  VocabItem('adverse', 'bất lợi'),
  VocabItem('advocacy', 'sự ủng hộ'),
  VocabItem('affiliation', 'sự liên kết'),
  VocabItem('agenda', 'chương trình nghị sự'),
  VocabItem('aggression', 'sự hung hăng'),
  VocabItem('agriculture', 'nông nghiệp'),
  VocabItem('alienation', 'sự xa lánh'),
  VocabItem('ambiguity', 'sự mơ hồ'),
  VocabItem('amendment', 'sự sửa đổi'),
  VocabItem('analogy', 'phép tương đồng'),
  VocabItem('anomaly', 'sự bất thường'),
  VocabItem('anticipation', 'sự mong đợi'),
  VocabItem('appraisal', 'sự đánh giá'),
  VocabItem('arbitration', 'trọng tài, phân xử'),
  VocabItem('architecture', 'kiến trúc'),
  VocabItem('articulation', 'sự diễn đạt rõ ràng'),
  VocabItem('aspiration', 'khát vọng'),
  VocabItem('assurance', 'sự đảm bảo'),
  VocabItem('authenticity', 'tính chân thực'),
  VocabItem('autonomy', 'sự tự chủ'),
  VocabItem('barrier', 'rào cản'),
  VocabItem('beneficiary', 'người thụ hưởng'),
  VocabItem('bureaucracy', 'quan liêu'),
  VocabItem('capability', 'năng lực'),
  VocabItem('causal', 'thuộc nguyên nhân'),
  VocabItem('coercion', 'sự cưỡng ép'),
  VocabItem('coherence', 'tính mạch lạc'),
  VocabItem('collaboration', 'sự hợp tác'),
  VocabItem('commitment', 'cam kết'),
  VocabItem('compassion', 'lòng trắc ẩn'),
  VocabItem('competence', 'năng lực'),
  VocabItem('compliance', 'sự tuân thủ'),
  VocabItem('concession', 'sự nhượng bộ'),
  VocabItem('confidential', 'bảo mật'),
  VocabItem('configuration', 'cấu hình'),
  VocabItem('consensus', 'đồng thuận'),
  VocabItem('constraint', 'sự hạn chế'),
  VocabItem('consultation', 'sự tham vấn'),
  VocabItem('contradiction', 'sự mâu thuẫn'),
  VocabItem('convergence', 'sự hội tụ'),
  VocabItem('correlation', 'mối tương quan'),
  VocabItem('credibility', 'độ tin cậy'),
  VocabItem('declaration', 'tuyên bố'),
  VocabItem('deduction', 'sự suy luận'),
  VocabItem('deficiency', 'sự thiếu hụt'),
  VocabItem('delegation', 'sự ủy quyền'),
  VocabItem('demographic', 'nhân khẩu học'),
  VocabItem('dependency', 'sự phụ thuộc'),
  VocabItem('deprivation', 'sự thiếu thốn'),
  VocabItem('designation', 'sự chỉ định'),
  VocabItem('detection', 'sự phát hiện'),
  VocabItem('deviation', 'sự lệch khỏi chuẩn'),
  VocabItem('diagnosis', 'chẩn đoán'),
  VocabItem('dilemma', 'tình thế khó xử'),
  VocabItem('dimension', 'khía cạnh, chiều'),
  VocabItem('discrimination', 'phân biệt đối xử'),
  VocabItem('disruption', 'sự gián đoạn'),
  VocabItem('distinction', 'sự khác biệt'),
  VocabItem('diversity', 'sự đa dạng'),
  VocabItem('documentation', 'tài liệu'),
  VocabItem('dominance', 'sự thống trị'),
  VocabItem('duration', 'thời lượng'),
  VocabItem('dynamics', 'động lực học, diễn biến'),
  VocabItem('ecosystem', 'hệ sinh thái'),
  VocabItem('eligibility', 'đủ điều kiện'),
  VocabItem('empathy', 'sự đồng cảm'),
  VocabItem('empowerment', 'trao quyền'),
  VocabItem('enforcement', 'việc thực thi'),
  VocabItem('engagement', 'sự gắn kết'),
  VocabItem('entitlement', 'quyền được hưởng'),
  VocabItem('entrepreneur', 'doanh nhân'),
  VocabItem('entrepreneurship', 'khởi nghiệp'),
  VocabItem('equity', 'công bằng'),
  VocabItem('establishment', 'sự thành lập'),
  VocabItem('exclusion', 'sự loại trừ'),
  VocabItem('expertise', 'chuyên môn'),
  VocabItem('exposure', 'sự tiếp xúc'),
  VocabItem('feasibility', 'tính khả thi'),
  VocabItem('formulation', 'sự hình thành'),
  VocabItem('framework', 'khung, hệ thống'),
  VocabItem('fulfillment', 'sự hoàn thành, thỏa mãn'),
  VocabItem('governance', 'quản trị'),
  VocabItem('guideline', 'hướng dẫn'),
  VocabItem('infrastructure', 'cơ sở hạ tầng'),
  VocabItem('inquiry', 'sự tìm hiểu, yêu cầu'),
  VocabItem('insight', 'hiểu biết sâu sắc'),
  VocabItem('integration', 'sự tích hợp'),
  VocabItem('intervention', 'sự can thiệp'),
  VocabItem('inventory', 'hàng tồn kho'),
  VocabItem('jurisdiction', 'thẩm quyền pháp lý'),
  VocabItem('legislation', 'pháp luật'),
  VocabItem('literacy', 'khả năng đọc viết'),
  VocabItem('logistics', 'hậu cần'),
  VocabItem('mechanism', 'cơ chế'),
  VocabItem('migration', 'di cư'),
  VocabItem('moderation', 'sự điều tiết'),
  VocabItem('neglect', 'sự sao nhãng'),
  VocabItem('networking', 'việc xây dựng quan hệ'),
  VocabItem('obligation', 'nghĩa vụ'),
  VocabItem('optimization', 'sự tối ưu hóa'),
  VocabItem('orientation', 'định hướng'),
  VocabItem('parameter', 'tham số'),
  VocabItem('partnership', 'mối quan hệ hợp tác'),
  VocabItem('perception', 'nhận thức'),
  VocabItem('persistence', 'sự kiên trì'),
  VocabItem('phenomenon', 'hiện tượng'),
  VocabItem('portfolio', 'danh mục đầu tư'),
  VocabItem('precedent', 'tiền lệ'),
  VocabItem('preservation', 'sự bảo tồn'),
  VocabItem('probability', 'xác suất'),
  VocabItem('provision', 'điều khoản, sự cung cấp'),
  VocabItem('proximity', 'sự gần gũi'),
  VocabItem('regulation', 'quy định'),
  VocabItem('reimbursement', 'sự hoàn tiền'),
  VocabItem('reinforcement', 'sự củng cố'),
  VocabItem('reliability', 'độ tin cậy'),
  VocabItem('remuneration', 'thù lao'),
  VocabItem('restriction', 'sự hạn chế'),
  VocabItem('retention', 'sự duy trì'),
  VocabItem('revenue', 'doanh thu'),
  VocabItem('reversal', 'sự đảo ngược'),
  VocabItem('safeguard', 'biện pháp bảo vệ'),
  VocabItem('scarcity', 'sự khan hiếm'),
  VocabItem('segmentation', 'sự phân khúc'),
  VocabItem('stakeholder', 'bên liên quan'),
  VocabItem('submission', 'sự nộp, bài nộp'),
  VocabItem('subsidy', 'trợ cấp'),
  VocabItem('supervision', 'giám sát'),
  VocabItem('transparency', 'minh bạch'),
  VocabItem('transition', 'sự chuyển đổi'),
  VocabItem('transmission', 'sự truyền tải'),
  VocabItem('uncertainty', 'sự không chắc chắn'),
  VocabItem('unemployment', 'thất nghiệp'),
  VocabItem('validation', 'sự xác nhận'),
  VocabItem('viability', 'tính khả thi'),
  VocabItem('volatility', 'sự biến động'),
  VocabItem('accountability', 'trách nhiệm giải trình'),
  VocabItem('acquisition', 'sự thu nhận, mua lại'),
  VocabItem('activation', 'sự kích hoạt'),
  VocabItem('administrative', 'thuộc quản lý'),
  VocabItem('analytical', 'thuộc phân tích'),
  VocabItem('artificial', 'nhân tạo'),
  VocabItem('cognitive', 'thuộc nhận thức'),
  VocabItem('collective', 'tập thể'),
  VocabItem('commercial', 'thương mại'),
  VocabItem('compatible', 'tương thích'),
  VocabItem('compulsory', 'bắt buộc'),
  VocabItem('conventional', 'thông thường, truyền thống'),
  VocabItem('corporate', 'thuộc doanh nghiệp'),
  VocabItem('creative', 'sáng tạo'),
  VocabItem('critical', 'quan trọng, mang tính phê phán'),
  VocabItem('decisive', 'quyết định'),
  VocabItem('deliberate', 'có chủ ý'),
  VocabItem('dynamic', 'năng động'),
  VocabItem('educational', 'thuộc giáo dục'),
  VocabItem('efficiently', 'một cách hiệu quả'),
  VocabItem('emotional', 'thuộc cảm xúc'),
  VocabItem('exceptional', 'đặc biệt xuất sắc'),
  VocabItem('exclusive', 'độc quyền'),
  VocabItem('experimental', 'thực nghiệm'),
  VocabItem('financially', 'về mặt tài chính'),
  VocabItem('global', 'toàn cầu'),
  VocabItem('historical', 'thuộc lịch sử'),
  VocabItem('informative', 'bổ ích, giàu thông tin'),
  VocabItem('institutional', 'thuộc tổ chức'),
  VocabItem('intellectual', 'thuộc trí tuệ'),
  VocabItem('legal', 'thuộc pháp lý'),
  VocabItem('logical', 'logic'),
  VocabItem('medical', 'thuộc y khoa'),
  VocabItem('operational', 'thuộc vận hành'),
  VocabItem('political', 'thuộc chính trị'),
  VocabItem('predictable', 'có thể dự đoán'),
  VocabItem('productive', 'có năng suất'),
  VocabItem('psychological', 'thuộc tâm lý'),
  VocabItem('regional', 'thuộc khu vực'),
  VocabItem('regulatory', 'thuộc quy định'),
  VocabItem('strategic', 'thuộc chiến lược'),
  VocabItem('technical', 'thuộc kỹ thuật'),
  VocabItem('theoretical', 'thuộc lý thuyết'),
  VocabItem('urban', 'thuộc đô thị'),
  VocabItem('visual', 'thuộc thị giác'),
  VocabItem('academic', 'thuộc học thuật'),
  VocabItem('annual', 'hàng năm'),
  VocabItem('automated', 'tự động hóa'),
  VocabItem('basic', 'cơ bản'),
  VocabItem('complex', 'phức tạp'),
  VocabItem('contemporary', 'đương đại'),
  VocabItem('digitalization', 'số hóa'),
  VocabItem('domestic', 'trong nước'),
  VocabItem('eligible', 'đủ điều kiện'),
  VocabItem('external', 'bên ngoài'),
  VocabItem('internal', 'nội bộ'),
  VocabItem('interactive', 'tương tác'),
  VocabItem('internationally', 'ở phạm vi quốc tế'),
  VocabItem('manual', 'thủ công'),
  VocabItem('mobile', 'di động'),
  VocabItem('online', 'trực tuyến'),
  VocabItem('optional', 'tùy chọn'),
  VocabItem('permanent', 'vĩnh viễn'),
  VocabItem('personalized', 'cá nhân hóa'),
  VocabItem('remote', 'từ xa'),
  VocabItem('secure', 'an toàn, bảo mật'),
  VocabItem('sophisticated', 'tinh vi'),
  VocabItem('stable', 'ổn định'),
  VocabItem('sustainable', 'bền vững'),
  VocabItem('virtual', 'ảo'),
  VocabItem('willing', 'sẵn lòng'),
  VocabItem('adapt', 'thích nghi'),
  VocabItem('administer', 'quản lý'),
  VocabItem('assemble', 'lắp ráp, tập hợp'),
  VocabItem('assess', 'đánh giá'),
  VocabItem('assign', 'giao, phân công'),
  VocabItem('boost', 'thúc đẩy'),
  VocabItem('calculate', 'tính toán'),
  VocabItem('capture', 'ghi lại, thu hút'),
  VocabItem('classify', 'phân loại'),
  VocabItem('coexist', 'cùng tồn tại'),
  VocabItem('collapse', 'sụp đổ'),
  VocabItem('combine', 'kết hợp'),
  VocabItem('communicate', 'giao tiếp'),
  VocabItem('comply', 'tuân thủ'),
  VocabItem('concentrate', 'tập trung'),
  VocabItem('conduct', 'tiến hành'),
  VocabItem('confront', 'đối mặt'),
  VocabItem('consolidate', 'củng cố'),
  VocabItem('construct', 'xây dựng'),
  VocabItem('consume', 'tiêu thụ'),
  VocabItem('convert', 'chuyển đổi'),
  VocabItem('cultivate', 'nuôi dưỡng'),
  VocabItem('debate', 'tranh luận'),
  VocabItem('decline', 'suy giảm'),
  VocabItem('dedicate', 'cống hiến'),
  VocabItem('detect', 'phát hiện'),
  VocabItem('differentiate', 'phân biệt'),
  VocabItem('disclose', 'tiết lộ'),
  VocabItem('dispose', 'loại bỏ'),
  VocabItem('distort', 'bóp méo'),
  VocabItem('diversify', 'đa dạng hóa'),
  VocabItem('draft', 'soạn thảo'),
  VocabItem('duplicate', 'sao chép'),
  VocabItem('emerge', 'xuất hiện'),
  VocabItem('emphasize', 'nhấn mạnh'),
  VocabItem('enforce', 'thực thi'),
  VocabItem('engage', 'tham gia'),
  VocabItem('estimate', 'ước tính'),
  VocabItem('exceed', 'vượt quá'),
  VocabItem('expand', 'mở rộng'),
  VocabItem('expose', 'phơi bày'),
  VocabItem('extract', 'trích xuất'),
  VocabItem('flourish', 'phát triển mạnh'),
  VocabItem('formulate', 'xây dựng, đề ra'),
  VocabItem('foster', 'thúc đẩy, nuôi dưỡng'),
  VocabItem('guarantee', 'đảm bảo'),
  VocabItem('illustrate', 'minh họa'),
  VocabItem('impose', 'áp đặt'),
  VocabItem('incentivize', 'tạo động lực'),
  VocabItem('incur', 'gánh chịu'),
  VocabItem('infer', 'suy ra'),
  VocabItem('innovate', 'đổi mới'),
  VocabItem('inquire', 'hỏi, tìm hiểu'),
  VocabItem('install', 'lắp đặt'),
  VocabItem('interpret', 'diễn giải'),
  VocabItem('investigate', 'điều tra'),
  VocabItem('isolate', 'cô lập'),
  VocabItem('maintain', 'duy trì'),
  VocabItem('maximize', 'tối đa hóa'),
  VocabItem('minimize', 'tối thiểu hóa'),
  VocabItem('modify', 'điều chỉnh'),
  VocabItem('monitor', 'theo dõi'),
  VocabItem('negotiate', 'đàm phán'),
  VocabItem('notify', 'thông báo'),
  VocabItem('oblige', 'bắt buộc'),
  VocabItem('overcome', 'vượt qua'),
  VocabItem('participate', 'tham gia'),
  VocabItem('perceive', 'nhận thấy'),
  VocabItem('prioritize', 'ưu tiên'),
  VocabItem('proceed', 'tiến hành'),
  VocabItem('propose', 'đề xuất'),
  VocabItem('qualify', 'đủ điều kiện'),
  VocabItem('reassure', 'trấn an'),
  VocabItem('reconcile', 'đối chiếu, hòa giải'),
  VocabItem('recover', 'phục hồi'),
  VocabItem('regulate', 'điều chỉnh, quản lý'),
  VocabItem('reinforce', 'củng cố'),
  VocabItem('relieve', 'giảm bớt'),
  VocabItem('resolve', 'giải quyết'),
  VocabItem('restore', 'khôi phục'),
  VocabItem('restrict', 'hạn chế'),
  VocabItem('retrieve', 'truy xuất'),
  VocabItem('revise', 'chỉnh sửa'),
  VocabItem('shift', 'chuyển đổi'),
  VocabItem('specify', 'nêu rõ'),
  VocabItem('strengthen', 'củng cố'),
  VocabItem('submit', 'nộp'),
  VocabItem('supplement', 'bổ sung'),
  VocabItem('transform', 'biến đổi'),
  VocabItem('transmit', 'truyền tải'),
  VocabItem('trigger', 'kích hoạt, gây ra'),
  VocabItem('upgrade', 'nâng cấp'),
  VocabItem('verify', 'xác minh'),
  VocabItem('accommodate', 'đáp ứng, sắp xếp chỗ'),
  VocabItem('adhere', 'tuân thủ'),
  VocabItem('adjust', 'điều chỉnh'),
  VocabItem('amend', 'sửa đổi'),
  VocabItem('approve', 'phê duyệt'),
  VocabItem('arise', 'phát sinh'),
  VocabItem('assure', 'đảm bảo'),
  VocabItem('authorize', 'ủy quyền'),
  VocabItem('broaden', 'mở rộng'),
  VocabItem('coincide', 'trùng hợp'),
  VocabItem('conceal', 'che giấu'),
  VocabItem('conclude', 'kết luận'),
  VocabItem('confer', 'trao đổi, trao tặng'),
  VocabItem('confirm', 'xác nhận'),
  VocabItem('confrontation', 'sự đối đầu'),
  VocabItem('contribute', 'đóng góp'),
  VocabItem('controversy', 'tranh cãi'),
  VocabItem('curb', 'kiềm chế'),
  VocabItem('defer', 'trì hoãn'),
  VocabItem('designate', 'chỉ định'),
  VocabItem('devise', 'nghĩ ra'),
  VocabItem('discriminate', 'phân biệt đối xử'),
  VocabItem('dismiss', 'bác bỏ, cho nghỉ'),
  VocabItem('disrupt', 'làm gián đoạn'),
  VocabItem('distinguish', 'phân biệt'),
  VocabItem('divert', 'chuyển hướng'),
  VocabItem('embark', 'bắt đầu, lên đường'),
  VocabItem('endure', 'chịu đựng'),
  VocabItem('envisage', 'hình dung'),
  VocabItem('evoke', 'gợi lên'),
  VocabItem('exaggerate', 'phóng đại'),
  VocabItem('exhibit', 'trưng bày, thể hiện'),
  VocabItem('hinder', 'cản trở'),
  VocabItem('imply', 'ngụ ý'),
  VocabItem('indicate', 'chỉ ra'),
  VocabItem('initiate', 'khởi xướng'),
  VocabItem('inspire', 'truyền cảm hứng'),
  VocabItem('interact', 'tương tác'),
  VocabItem('launch', 'ra mắt, khởi động'),
  VocabItem('merge', 'sáp nhập'),
  VocabItem('oversee', 'giám sát'),
  VocabItem('prompt', 'thúc đẩy, nhắc'),
  VocabItem('render', 'trình bày, khiến'),
  VocabItem('reside', 'cư trú'),
  VocabItem('seek', 'tìm kiếm'),
  VocabItem('speculate', 'suy đoán'),
  VocabItem('substitute', 'thay thế'),
  VocabItem('suspend', 'tạm dừng'),
  VocabItem('tackle', 'giải quyết'),
  VocabItem('underestimate', 'đánh giá thấp'),
  VocabItem('undertake', 'đảm nhận'),
  VocabItem('validate', 'xác nhận tính hợp lệ'),
  VocabItem('warrant', 'biện minh, bảo đảm'),
  VocabItem('ambiguously', 'một cách mơ hồ'),
  VocabItem('consistently', 'một cách nhất quán'),
  VocabItem('considerably', 'đáng kể'),
  VocabItem('consequently', 'do đó'),
  VocabItem('deliberately', 'cố ý'),
  VocabItem('explicitly', 'một cách rõ ràng'),
  VocabItem('fundamentally', 'về cơ bản'),
  VocabItem('increasingly', 'ngày càng'),
  VocabItem('inevitably', 'không thể tránh khỏi'),
  VocabItem('largely', 'phần lớn'),
  VocabItem('merely', 'chỉ đơn thuần'),
  VocabItem('notably', 'đáng chú ý'),
  VocabItem('predominantly', 'chủ yếu'),
  VocabItem('relatively', 'tương đối'),
  VocabItem('roughly', 'xấp xỉ'),
  VocabItem('simultaneously', 'đồng thời'),
  VocabItem('specifically', 'cụ thể'),
  VocabItem('subsequently', 'sau đó'),
  VocabItem('theoretically', 'về lý thuyết'),
  VocabItem('ultimately', 'cuối cùng'),
  VocabItem('virtually', 'gần như'),
  VocabItem('accordingly', 'theo đó'),
  VocabItem('alternatively', 'hoặc theo cách khác'),
  VocabItem('comparatively', 'tương đối'),
  VocabItem('conversely', 'ngược lại'),
  VocabItem('inherently', 'vốn dĩ'),
  VocabItem('jointly', 'cùng nhau'),
  VocabItem('primarily', 'chủ yếu'),
  VocabItem('respectively', 'lần lượt'),
  VocabItem('solely', 'chỉ, duy nhất'),
  VocabItem('undoubtedly', 'không nghi ngờ gì'),
  VocabItem('adversely', 'theo hướng bất lợi'),
  VocabItem('adequately', 'một cách đầy đủ'),
  VocabItem('briefly', 'một cách ngắn gọn'),
  VocabItem('closely', 'sát sao'),
  VocabItem('commonly', 'thường'),
  VocabItem('critically', 'một cách quan trọng'),
  VocabItem('effectively', 'một cách hiệu quả'),
  VocabItem('equally', 'đồng đều'),
  VocabItem('extensively', 'rộng rãi'),
  VocabItem('generally', 'nhìn chung'),
  VocabItem('highly', 'rất, cao'),
  VocabItem('independently', 'độc lập'),
  VocabItem('initially', 'ban đầu'),
  VocabItem('mainly', 'chủ yếu'),
  VocabItem('necessarily', 'nhất thiết'),
  VocabItem('partially', 'một phần'),
  VocabItem('potentially', 'có khả năng'),
  VocabItem('precisely', 'một cách chính xác'),
  VocabItem('previously', 'trước đây'),
  VocabItem('promptly', 'ngay lập tức'),
  VocabItem('rarely', 'hiếm khi'),
  VocabItem('regularly', 'thường xuyên'),
  VocabItem('significantly', 'đáng kể'),
  VocabItem('strongly', 'mạnh mẽ'),
  VocabItem('temporarily', 'tạm thời'),
  VocabItem('typically', 'điển hình'),
  VocabItem('widely', 'rộng rãi'),
  VocabItem('analyst', 'nhà phân tích'),
  VocabItem('anthropologist', 'nhà nhân loại học'),
  VocabItem('architect', 'kiến trúc sư'),
  VocabItem('biologist', 'nhà sinh vật học'),
  VocabItem('consultant', 'chuyên gia tư vấn'),
  VocabItem('economist', 'nhà kinh tế học'),
  VocabItem('engineer', 'kỹ sư'),
  VocabItem('journalist', 'nhà báo'),
  VocabItem('legislator', 'nhà lập pháp'),
  VocabItem('mathematician', 'nhà toán học'),
  VocabItem('philosopher', 'nhà triết học'),
  VocabItem('physician', 'bác sĩ'),
  VocabItem('psychologist', 'nhà tâm lý học'),
  VocabItem('researcher', 'nhà nghiên cứu'),
  VocabItem('scientist', 'nhà khoa học'),
  VocabItem('specialist', 'chuyên gia'),
  VocabItem('technician', 'kỹ thuật viên'),
  VocabItem('theorist', 'nhà lý thuyết'),
  VocabItem('translator', 'biên dịch viên'),
  VocabItem('administrator', 'quản trị viên'),
  VocabItem('ambassador', 'đại sứ'),
  VocabItem('candidate', 'ứng viên'),
  VocabItem('colleague', 'đồng nghiệp'),
  VocabItem('competitor', 'đối thủ'),
  VocabItem('consumer', 'người tiêu dùng'),
  VocabItem('contributor', 'người đóng góp'),
  VocabItem('defendant', 'bị đơn'),
  VocabItem('employee', 'nhân viên'),
  VocabItem('employer', 'người sử dụng lao động'),
  VocabItem('executive', 'quản lý cấp cao'),
  VocabItem('founder', 'người sáng lập'),
  VocabItem('investor', 'nhà đầu tư'),
  VocabItem('manager', 'quản lý'),
  VocabItem('negotiator', 'nhà đàm phán'),
  VocabItem('passenger', 'hành khách'),
  VocabItem('pedestrian', 'người đi bộ'),
  VocabItem('resident', 'cư dân'),
  VocabItem('shareholder', 'cổ đông'),
  VocabItem('supervisor', 'người giám sát'),
  VocabItem('volunteer', 'tình nguyện viên'),
  VocabItem('witness', 'nhân chứng'),
  VocabItem('workforce', 'lực lượng lao động'),
  VocabItem('agency', 'cơ quan'),
  VocabItem('association', 'hiệp hội'),
  VocabItem('committee', 'ủy ban'),
  VocabItem('institution', 'tổ chức'),
  VocabItem('organization', 'tổ chức'),
  VocabItem('sector', 'ngành, khu vực'),
  VocabItem('enterprise', 'doanh nghiệp'),
  VocabItem('industry', 'ngành công nghiệp'),
  VocabItem('corporation', 'tập đoàn'),
  VocabItem('foundation', 'nền tảng, quỹ'),
  VocabItem('headquarters', 'trụ sở chính'),
  VocabItem('department', 'phòng ban'),
  VocabItem('division', 'bộ phận'),
  VocabItem('facility', 'cơ sở'),
  VocabItem('laboratory', 'phòng thí nghiệm'),
  VocabItem('workshop', 'xưởng, hội thảo'),
  VocabItem('conference', 'hội nghị'),
  VocabItem('seminar', 'hội thảo'),
  VocabItem('symposium', 'hội thảo chuyên đề'),
  VocabItem('curriculum', 'chương trình học'),
  VocabItem('assignment', 'bài tập'),
  VocabItem('certificate', 'chứng chỉ'),
  VocabItem('credential', 'bằng cấp, chứng nhận'),
  VocabItem('degree', 'bằng cấp'),
  VocabItem('scholarship', 'học bổng'),
  VocabItem('tuition', 'học phí'),
  VocabItem('faculty', 'giảng viên, khoa'),
  VocabItem('lecture', 'bài giảng'),
  VocabItem('thesis', 'luận văn'),
  VocabItem('dissertation', 'luận án'),
  VocabItem('literature', 'văn học, tài liệu'),
  VocabItem('methodology', 'phương pháp luận'),
  VocabItem('research', 'nghiên cứu'),
  VocabItem('evidence', 'bằng chứng'),
  VocabItem('finding', 'phát hiện'),
  VocabItem('theory', 'lý thuyết'),
  VocabItem('concept', 'khái niệm'),
  VocabItem('variable', 'biến số'),
  VocabItem('sample', 'mẫu'),
  VocabItem('survey', 'khảo sát'),
  VocabItem('dataset', 'tập dữ liệu'),
  VocabItem('statistics', 'số liệu thống kê'),
  VocabItem('validity', 'độ giá trị'),
  VocabItem('publication', 'ấn phẩm'),
  VocabItem('citation', 'trích dẫn'),
  VocabItem('reference', 'tài liệu tham khảo'),
  VocabItem('peer', 'đồng nghiệp, người cùng cấp'),
  VocabItem('review', 'đánh giá, bài nhận xét'),
  VocabItem('innovation', 'đổi mới'),
  VocabItem('invention', 'phát minh'),
  VocabItem('patent', 'bằng sáng chế'),
  VocabItem('prototype', 'mẫu thử'),
  VocabItem('software', 'phần mềm'),
  VocabItem('hardware', 'phần cứng'),
  VocabItem('database', 'cơ sở dữ liệu'),
  VocabItem('network', 'mạng'),
  VocabItem('algorithm', 'thuật toán'),
  VocabItem('automation', 'tự động hóa'),
  VocabItem('artificial intelligence', 'trí tuệ nhân tạo'),
  VocabItem('biotechnology', 'công nghệ sinh học'),
  VocabItem('cybersecurity', 'an ninh mạng'),
  VocabItem('encryption', 'mã hóa'),
  VocabItem('interface', 'giao diện'),
  VocabItem('platform', 'nền tảng'),
  VocabItem('protocol', 'giao thức'),
  VocabItem('server', 'máy chủ'),
  VocabItem('storage', 'lưu trữ'),
  VocabItem('bandwidth', 'băng thông'),
  VocabItem('browser', 'trình duyệt'),
  VocabItem('application', 'ứng dụng'),
  VocabItem('device', 'thiết bị'),
  VocabItem('economy', 'nền kinh tế'),
  VocabItem('inflation', 'lạm phát'),
  VocabItem('recession', 'suy thoái'),
  VocabItem('investment', 'đầu tư'),
  VocabItem('interest rate', 'lãi suất'),
  VocabItem('mortgage', 'khoản vay thế chấp'),
];

const allVocabulary = <VocabItem>[...easyVerbs, ...everydayWords, ...advancedWords];
