class PromptOption {
  final String id;
  final String categoryKey;
  final String categoryVi;
  final String categoryEn;
  final String questionVi;
  final String questionEn;
  final List<String> aiSuggestionsVi;
  final List<String> aiSuggestionsEn;

  const PromptOption({
    required this.id,
    required this.categoryKey,
    required this.categoryVi,
    required this.categoryEn,
    required this.questionVi,
    required this.questionEn,
    required this.aiSuggestionsVi,
    required this.aiSuggestionsEn,
  });
}

const List<PromptOption> kPromptOptions = [
  PromptOption(
    id: 'love_1',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Tình yêu với tôi là...",
    questionEn: "Love, to me, is...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_2',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Một mối quan hệ đẹp trong mắt tôi là...",
    questionEn: "A beautiful relationship, to me, is...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_3',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Điều tôi cần nhất trong tình yêu là...",
    questionEn: "What I need most in love is...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_4',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Green flag khiến tôi rung động là...",
    questionEn: "A green flag that instantly gets my attention is...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_5',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Red flag khiến tôi e ngại là...",
    questionEn: "A red flag for me is...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_6',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Tôi thể hiện tình cảm bằng cách...",
    questionEn: "I show affection by...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_7',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Điều nhỏ trong tình yêu khiến tôi hạnh phúc là...",
    questionEn: "A small thing in love that makes me happy is...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_8',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Khi yêu, tôi mong cả hai sẽ...",
    questionEn: "In a relationship, I hope we both will...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_9',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Tôi nghĩ sự chung thủy là...",
    questionEn: "To me, loyalty means...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_10',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Một cuộc hẹn khiến tôi nhớ mãi là...",
    questionEn: "A date I would always remember is...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'love_11',
    categoryKey: 'love',
    categoryVi: "Tình yêu",
    categoryEn: "Love",
    questionVi: "Tôi thấy hấp dẫn nhất ở một người là...",
    questionEn: "What I find most attractive in someone is...",
    aiSuggestionsVi: [
      "Tôi tin điều đẹp nhất là hai người luôn chọn nhau bằng sự chân thành và bình yên.",
      "Với tôi, điều quan trọng nhất là cảm giác an toàn, được lắng nghe và được tôn trọng.",
      "Tôi thích một kết nối rõ ràng, ấm áp và đủ trưởng thành để cùng nhau đi đường dài.",
      "Tình cảm đẹp là khi cả hai vừa là người yêu, vừa là người đồng hành trong cuộc sống.",
      "Tôi trân trọng những điều nhỏ như sự quan tâm đều đặn, lời nói thật lòng và sự hiện diện.",
      "Tôi bị thu hút bởi người biết yêu bằng hành động, giao tiếp rõ ràng và giữ lời.",
    ],
    aiSuggestionsEn: [
      "I believe the most beautiful thing is when two people keep choosing each other with honesty and peace.",
      "What matters most to me is feeling safe, heard, and respected.",
      "I am drawn to a connection that is clear, warm, and mature enough to grow long-term.",
      "A great relationship, to me, is when two people are both lovers and teammates.",
      "I value the small things—consistent care, honest words, and showing up for each other.",
      "I am most attracted to someone who loves through actions, communicates clearly, and keeps their word.",
    ],
  ),
  PromptOption(
    id: 'personality_1',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Ba từ mô tả tôi rõ nhất là...",
    questionEn: "The three words that describe me best are...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_2',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Bạn bè thường nói tôi là người...",
    questionEn: "My friends would describe me as someone who is...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_3',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Điểm khiến tôi khác biệt là...",
    questionEn: "What makes me different is...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_4',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Một điều tôi tự hào về bản thân là...",
    questionEn: "One thing I am proud of about myself is...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_5',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Tôi là kiểu người sẽ...",
    questionEn: "I am the kind of person who will...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_6',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Khi ở cạnh người thân thiết, tôi thường...",
    questionEn: "When I am with people I trust, I usually...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_7',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Siêu năng lực đời thường của tôi là...",
    questionEn: "My everyday superpower is...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_8',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Một thói quen đáng yêu của tôi là...",
    questionEn: "One cute habit I have is...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_9',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Điều khiến tôi thấy mình trưởng thành hơn là...",
    questionEn: "What makes me feel more mature is...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_10',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Nếu phải nói thật về mình, tôi là người...",
    questionEn: "If I am being honest, I am someone who...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'personality_11',
    categoryKey: 'personality',
    categoryVi: "Tính cách",
    categoryEn: "Personality",
    questionVi: "Năng lượng của tôi thường là...",
    questionEn: "My energy is usually...",
    aiSuggestionsVi: [
      "Tôi là người ấm áp, chân thành và thường để ý những chi tiết nhỏ.",
      "Tôi sống tình cảm nhưng cũng khá rõ ràng trong điều mình muốn và điều mình trân trọng.",
      "Khi thân rồi, tôi vui tính hơn mọi người nghĩ và rất thích tạo cảm giác thoải mái cho người bên cạnh.",
      "Tôi xem sự tử tế, đáng tin và biết lắng nghe là những điểm rất quan trọng ở bản thân.",
      "Tôi thích sống nhẹ nhàng nhưng nghiêm túc khi cần, và luôn cố gắng cư xử tinh tế.",
      "Điểm mạnh của tôi là biết cân bằng giữa cảm xúc, trách nhiệm và sự chân thành.",
    ],
    aiSuggestionsEn: [
      "I am warm, genuine, and usually notice the little details.",
      "I am emotionally sincere, but also clear about what I want and value.",
      "Once I feel comfortable, I am more playful than people expect and I love making others feel at ease.",
      "Kindness, dependability, and listening well are traits I care deeply about.",
      "I like to live gently, but I can be serious when needed and I try to be thoughtful in how I treat people.",
      "One of my strengths is balancing emotion, responsibility, and sincerity.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_1',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Một ngày lý tưởng của tôi là...",
    questionEn: "My ideal day looks like...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_2',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Cuối tuần tôi thích...",
    questionEn: "On weekends, I love to...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_3',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Buổi tối hoàn hảo với tôi là...",
    questionEn: "My perfect evening is...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_4',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Tôi nạp lại năng lượng bằng cách...",
    questionEn: "I recharge by...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_5',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Một niềm vui nhỏ mỗi ngày của tôi là...",
    questionEn: "One small joy in my day is...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_6',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Tôi hợp nhất với người có lối sống...",
    questionEn: "I match best with someone whose lifestyle is...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_7',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Quán cà phê hay bữa tối yên tĩnh? Tôi chọn...",
    questionEn: "Coffee date or quiet dinner? I choose...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_8',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Điều tôi luôn cố giữ trong cuộc sống là...",
    questionEn: "One thing I always try to keep in my life is...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_9',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Khi rảnh, tôi thường...",
    questionEn: "When I have free time, I usually...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_10',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Một kế hoạch ngẫu hứng tôi sẵn sàng đồng ý là...",
    questionEn: "A spontaneous plan I would say yes to is...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'lifestyle_11',
    categoryKey: 'lifestyle',
    categoryVi: "Lối sống",
    categoryEn: "Lifestyle",
    questionVi: "Cuộc sống cân bằng với tôi là...",
    questionEn: "A balanced life, to me, is...",
    aiSuggestionsVi: [
      "Tôi thích một nhịp sống cân bằng: làm việc tử tế, nghỉ ngơi đủ và dành thời gian cho những người quan trọng.",
      "Một ngày đẹp với tôi thường có đồ ăn ngon, một cuộc trò chuyện thật và cảm giác lòng mình nhẹ nhàng.",
      "Tôi không cần mọi thứ quá ồn ào, chỉ cần đúng người và đúng không khí là đã rất vui rồi.",
      "Cuối tuần lý tưởng của tôi là vừa thư giãn, vừa làm điều gì đó nhỏ mà đáng nhớ.",
      "Tôi thích những niềm vui đơn giản như cà phê ngon, đi dạo, nghe nhạc và cười nhiều hơn một chút.",
      "Tôi hợp với người biết tận hưởng cuộc sống nhưng vẫn có trách nhiệm và sự ổn định.",
    ],
    aiSuggestionsEn: [
      "I enjoy a balanced rhythm: doing good work, resting well, and making time for the people who matter.",
      "A good day for me usually includes good food, a real conversation, and a sense of inner calm.",
      "I do not need everything to be loud or flashy—if the person and the vibe are right, I am happy.",
      "My ideal weekend is a mix of rest and one small memorable thing.",
      "I enjoy simple joys like good coffee, a walk, music, and laughing a little more.",
      "I match well with someone who enjoys life but still values responsibility and stability.",
    ],
  ),
  PromptOption(
    id: 'family_1',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Gia đình có ý nghĩa với tôi là...",
    questionEn: "Family means... to me",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_2',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Điều tôi trân trọng nhất trong một gia đình là...",
    questionEn: "What I value most in a family is...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_3',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Một mái ấm lý tưởng với tôi là...",
    questionEn: "A dream home life for me is...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_4',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Tôi học được từ gia đình mình rằng...",
    questionEn: "What I learned from my family is...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_5',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Tôi thấy ấm lòng nhất khi...",
    questionEn: "I feel most at home when...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_6',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Một bữa cơm gia đình đẹp trong mắt tôi là...",
    questionEn: "A beautiful family meal, to me, is...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_7',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Điều tôi muốn mang vào gia đình tương lai là...",
    questionEn: "What I want to bring into my future family is...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_8',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Tôi tin rằng một gia đình hạnh phúc cần...",
    questionEn: "I believe a happy family needs...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_9',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Tôi luôn trân trọng người biết...",
    questionEn: "I deeply value someone who knows how to...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_10',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Kỷ niệm gia đình khiến tôi mỉm cười là...",
    questionEn: "A family memory that makes me smile is...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'family_11',
    categoryKey: 'family',
    categoryVi: "Gia đình",
    categoryEn: "Family",
    questionVi: "Khi nghĩ về tương lai, tôi mong mái ấm của mình sẽ...",
    questionEn: "When I think about the future, I hope my home will...",
    aiSuggestionsVi: [
      "Gia đình với tôi là nơi có sự yêu thương thật lòng, tôn trọng và cảm giác được trở về.",
      "Tôi luôn trân trọng một mái ấm có sự ấm áp, tử tế và mọi người thật sự lắng nghe nhau.",
      "Tôi tin những điều bền lâu thường được xây từ những hành động nhỏ nhưng đều đặn mỗi ngày.",
      "Điều tôi muốn giữ trong gia đình tương lai là sự bình yên, chân thành và cảm giác cùng một phía.",
      "Tôi rất quý người biết quan tâm đến gia đình và cư xử nhẹ nhàng với người thân.",
      "Với tôi, một gia đình đẹp không cần hoàn hảo, chỉ cần có tình thương và sự đồng hành.",
    ],
    aiSuggestionsEn: [
      "Family, to me, is where genuine love, respect, and a sense of belonging live.",
      "I deeply value a home that feels warm, kind, and full of real listening.",
      "I believe lasting things are often built through small but consistent actions every day.",
      "What I want in a future family is peace, sincerity, and the feeling that we are on the same side.",
      "I really admire someone who cares about family and treats loved ones gently.",
      "To me, a beautiful family does not need to be perfect—it just needs love and togetherness.",
    ],
  ),
  PromptOption(
    id: 'future_1',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Tôi đang tìm kiếm...",
    questionEn: "I am looking for...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_2',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Tương lai lý tưởng của tôi là...",
    questionEn: "My ideal future is...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_3',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Trong vài năm tới, tôi muốn...",
    questionEn: "In the next few years, I want to...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_4',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Một mục tiêu tôi đang âm thầm theo đuổi là...",
    questionEn: "One goal I am quietly working toward is...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_5',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Tôi muốn xây dựng cuộc sống với người...",
    questionEn: "I want to build a life with someone who...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_6',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Điều khiến tôi sẵn sàng cho một mối quan hệ nghiêm túc là...",
    questionEn: "What makes me ready for a serious relationship is...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_7',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Một tương lai đủ đầy với tôi là...",
    questionEn: "A fulfilling future, to me, is...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_8',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Khi nghĩ đến người đồng hành lâu dài, tôi mong họ...",
    questionEn: "When I think about a long-term partner, I hope they...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_9',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Tôi tin hạnh phúc lâu dài đến từ...",
    questionEn: "I believe lasting happiness comes from...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_10',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Ước mơ giản dị nhưng quan trọng của tôi là...",
    questionEn: "A simple but important dream of mine is...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
  PromptOption(
    id: 'future_11',
    categoryKey: 'future',
    categoryVi: "Tương lai",
    categoryEn: "Future",
    questionVi: "Nếu gặp đúng người, tôi muốn cùng họ...",
    questionEn: "If I meet the right person, I would love to...",
    aiSuggestionsVi: [
      "Tôi đang hướng đến một cuộc sống ổn định, có ý nghĩa và có một người đồng hành thật lòng.",
      "Tôi muốn xây dựng một mối quan hệ rõ ràng, trưởng thành và đủ dịu dàng để đi lâu dài.",
      "Tương lai đẹp với tôi là có sự bình yên, phát triển và niềm vui giản dị mỗi ngày.",
      "Tôi bị thu hút bởi những người biết mình muốn gì và thật sự nghiêm túc khi cần.",
      "Tôi tin hạnh phúc lâu dài đến từ sự chọn nhau mỗi ngày, chứ không chỉ từ cảm xúc ban đầu.",
      "Nếu gặp đúng người, tôi muốn cùng họ xây một cuộc sống vừa ấm áp vừa vững vàng.",
    ],
    aiSuggestionsEn: [
      "I am moving toward a life that feels stable, meaningful, and shared with someone sincere.",
      "I want to build a relationship that is clear, mature, and gentle enough to last.",
      "A beautiful future, to me, looks like peace, growth, and simple daily joy.",
      "I am drawn to people who know what they want and can be serious when it matters.",
      "I believe lasting happiness comes from choosing each other every day, not just from the first spark.",
      "If I meet the right person, I would love to build a life that feels both warm and solid.",
    ],
  ),
];